// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package tutorial

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
  name,
  code
) VALUES ($1, $2) RETURNING id, name, code, created_at
`

type CreateCourseParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse, arg.Name, arg.Code)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  customer_id
) VALUES ($1) RETURNING id, customer_id, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(&i.ID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_cents)
VALUES ($1, $2, $3, $4) RETURNING id, order_id, product_id, quantity, price_cents
`

type CreateOrderItemParams struct {
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int32 `json:"quantity"`
	PriceCents int32 `json:"price_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceCents,
	)
	return i, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (
  course_id,
  week_number,
  date_time,
  status
) VALUES ($1, $2, $3, $4) RETURNING id, course_id, week_number, date_time, status, created_at
`

type CreateQuizParams struct {
	CourseID   int64              `json:"course_id"`
	WeekNumber pgtype.Int4        `json:"week_number"`
	DateTime   pgtype.Timestamptz `json:"date_time"`
	Status     string             `json:"status"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.CourseID,
		arg.WeekNumber,
		arg.DateTime,
		arg.Status,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.WeekNumber,
		&i.DateTime,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE
  id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const deleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM quizzes
WHERE
  id = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuiz, id)
	return err
}

const findCourseByID = `-- name: FindCourseByID :one
SELECT
    id, name, code, created_at
FROM
    courses
WHERE
    id = $1
`

func (q *Queries) FindCourseByID(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, findCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const findProductByID = `-- name: FindProductByID :one
SELECT
    id, name, price_in_cents, quantity, created_at
FROM
    products
WHERE
    id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const findQuizByID = `-- name: FindQuizByID :one
SELECT
    id, course_id, week_number, date_time, status, created_at
FROM
    quizzes
WHERE
    id = $1
`

func (q *Queries) FindQuizByID(ctx context.Context, id int64) (Quiz, error) {
	row := q.db.QueryRow(ctx, findQuizByID, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.WeekNumber,
		&i.DateTime,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT
    id, name, code, created_at
FROM
    courses
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    id, name, price_in_cents, quantity, created_at
FROM
    products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizzes = `-- name: ListQuizzes :many
SELECT
    id, course_id, week_number, date_time, status, created_at
FROM
    quizzes
`

func (q *Queries) ListQuizzes(ctx context.Context) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, listQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.WeekNumber,
			&i.DateTime,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET
  name = $2,
  code = $3
WHERE
  id = $1
RETURNING id, name, code, created_at
`

type UpdateCourseParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse, arg.ID, arg.Name, arg.Code)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes
SET
  week_number = $2,
  date_time = $3,
  status = $4
WHERE
  id = $1
RETURNING id, course_id, week_number, date_time, status, created_at
`

type UpdateQuizParams struct {
	ID         int64              `json:"id"`
	WeekNumber pgtype.Int4        `json:"week_number"`
	DateTime   pgtype.Timestamptz `json:"date_time"`
	Status     string             `json:"status"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz,
		arg.ID,
		arg.WeekNumber,
		arg.DateTime,
		arg.Status,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.WeekNumber,
		&i.DateTime,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
