// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tutorial

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	DeleteCourse(ctx context.Context, id int64) error
	FindCourseByID(ctx context.Context, id int64) (Course, error)
	FindProductByID(ctx context.Context, id int64) (Product, error)
	ListCourses(ctx context.Context) ([]Course, error)
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
}

var _ Querier = (*Queries)(nil)
